### PR TITLE
Added flags and coverage computation for skip

### LINKED ISSUE #36: Add coverage flags to skip() in IterImplSkip.java
There should be coverage flags in the skip() function as well as appropriate code in testing to measure the coverage.

### PR DESCRIPTION
**Pull request by francislaus**
Added flag statements for every branch in the function skip and
implemented a function to compute the percentage.
This should resolve #36

### CODE REVIEW

**Comment by Samuelhertzberg** [comment]
The case statements without a return/break will continue to the case statement below it. This means that if any of the statements "-" and [0-7] will set more flags than it should.  Wont it?

**Review by apeinot — APPROVED** [review]
Good ad-hoc coverage

**Comment by apeinot** [comment]
> The case statements without a return/break will continue to the case statement below it. This means that if any of the statements "-" and [0-7] will set more flags than it should. Wont it?

Even if there is no exit point in a branch, this branch should be considered so Franz is rigth

**Review by Samuelhertzberg — CHANGES_REQUESTED** [review]
The case statements without a return/break will continue to the case statement below it. This means that if any of the statements "-" and [0-7] will set more flags than it should.

**Comment by Samuelhertzberg** [comment]
> > The case statements without a return/break will continue to the case statement below it. This means that if any of the statements "-" and [0-7] will set more flags than it should. Wont it?
> 
> Even if there is no exit point in a branch, this branch should be considered so Franz is rigth

Yes but now the flags are set in an incorrect way. for example case 8 will always be set to true if case - or 0-7 ever happens. This can lead to a falsely higher coverage percentage.

**Comment by apeinot** [comment]
> > > The case statements without a return/break will continue to the case statement below it. This means that if any of the statements "-" and [0-7] will set more flags than it should. Wont it?
> > 
> > 
> > Even if there is no exit point in a branch, this branch should be considered so Franz is rigth
> 
> Yes but now the flags are set in an incorrect way. for example case 8 will always be set to true if case - or 0-7 ever happens. This can lead to a falsely higher coverage percentage.

No. Case '8' is set to true only if you find an '8'. As each case is a branch, you should flag any no matter of the exit points. I think we should a third point of view to be sure

**Comment by Samuelhertzberg** [comment]
> > > > The case statements without a return/break will continue to the case statement below it. This means that if any of the statements "-" and [0-7] will set more flags than it should. Wont it?
> > > 
> > > 
> > > Even if there is no exit point in a branch, this branch should be considered so Franz is rigth
> > 
> > 
> > Yes but now the flags are set in an incorrect way. for example case 8 will always be set to true if case - or 0-7 ever happens. This can lead to a falsely higher coverage percentage.
> 
> No. Case '8' is set to true only if you find an '8'. As each case is a branch, you should flag any no matter of the exit points. I think we should a third point of view to be sure

No case 8 is not only set that way. Consider this code:
`
String s = "A";
switch (s) {
            case "A":
                System.out.println("Hello ");
            case "B":
                System.out.println("there ");
            case "C":
                System.out.println("Alexandre ");
            default:
                System.out.println("This is wrong");
        }`
This code will output:
`
Hello 
there 
Alexandre
This is wrong
`
Setting flags in these case statements will lead to flags getting set to true even though the value is not correct

Sure lets get a third person!

**Comment by Jonagoo** [comment]
Cases without a break will fall through to the next case and execute any code there as well, it works like Samuel says. I think the best way would be to write *cover_skip[1] = (c == '-')* and so on, to make sure you actually took that branch and didn't fall through from a previous one.

**Comment by emilelm96** [comment]
I agree with Jonathan.

**Comment by francislaus** [comment]
I agree with you guys. I cannot change the logic of the function itself, but this is definitely the best solution.

**Review by emilelm96 — APPROVED** [review]

**Review by Jonagoo — APPROVED** [review]

**Review by Samuelhertzberg — APPROVED** [review]

**Pull request merged**
