### PR TITLE
Add flag and test for computing branch coverage of readStringSlowPath…

### LINKED ISSUE #56: Add coverage flags for readStringSlowPath in IterImpl.java
Implement ad-hoc coverage for this function

### PR DESCRIPTION
**Pull request by apeinot**
… in IterImpl.java

This should resolve #56

### CODE REVIEW

**Review by francislaus — CHANGES_REQUESTED** [review]
I think that `cover_readStringSlowPath[33] = true;` should not be there. This should already be covered by `cover_readStringSlowPath[0] = true;` Furthermore, I am not sure whether `cover_readStringSlowPath[34] = true;` is necessary. I think a try scope is not a branch, but all catch statements are.

**Comment by apeinot** [comment]
> I think that `cover_readStringSlowPath[33] = true;` should not be there. This should already be covered by `cover_readStringSlowPath[0] = true;` Furthermore, I am not sure whether `cover_readStringSlowPath[34] = true;` is necessary. I think a try scope is not a branch, but all catch statements are.

For the 33, I'm not sure. But I think the 34 is necessary, because you reach this throw only if nothing is return during the for and if I don't add a flag, we don't know if it's covered

**Comment by francislaus** [comment]
> > I think that `cover_readStringSlowPath[33] = true;` should not be there. This should already be covered by `cover_readStringSlowPath[0] = true;` Furthermore, I am not sure whether `cover_readStringSlowPath[34] = true;` is necessary. I think a try scope is not a branch, but all catch statements are.
> 
> For the 33, I'm not sure. But I think the 34 is necessary, because you reach this throw only if nothing is return during the for and if I don't add a flag, we don't know if it's covered

I agree that we don't know whether it is covered or not, but I think our task is to implement branch coverage and not statement coverage. Maybe, we need some other opinions on this pull request.

**Comment by emilelm96** [comment]
I'm not sure about this actually to be honest.

**Comment by Samuelhertzberg** [comment]
I agree with @apeinot on flag 34  but I think 33 should be removed.

**Review by emilelm96 — APPROVED** [review]

**Review by francislaus — APPROVED** [review]

**Pull request merged**
