### PR TITLE
Four new test cases for createEncoder

### LINKED ISSUE #46: Add tests for createEncoder
There should be three relatively easy tests to improve coverage that can be implemented on createEncoder. Specially for the statements:
´else if (c == '\u2028')´,
´else if (c == '\u2029')´ and
if (c > SURR1_LAST).

### PR DESCRIPTION
**Pull request by Samuelhertzberg**
Implemented 4 new test cases for the createEncoder class. The tests are simple edge case tests.
I added them in a new class called "TestMoreCoverageCreateEncoder.java". Also I added this file the test suite 'all' should resolve #46 AND #26 Since I did all four tests in one go.

### CODE REVIEW

**Comment by emilelm96** [comment]
You forgot to add JavaDoc to the two last tests. Other than that, it's great!

**Review by apeinot — APPROVED** [review]
You test looks good. Apart from what @emilelmarsson requested, your tests should be added to the same file as @emilelmarsson tests because they address the same file (GsonCompatibilityMode).

**Comment by Samuelhertzberg** [comment]
> You test looks good. Apart from what @emilelmarsson requested, your tests should be added to the same file as @emilelmarsson tests because they address the same file (GsonCompatibilityMode).

How is that best made? Renaming the file to the same name and then resolve merge conflict?

**Comment by Samuelhertzberg** [comment]
Done @emilelmarsson

**Review by emilelm96 — APPROVED** [review]

**Pull request merged**
