### PR TITLE
Finished the description of createDecoder() #18

### LINKED ISSUE #18: Add description of createDecoder() in GsonCompatibilityMode.java
Writing a description detailing the purpose of the function createDecoder(), the complexity and discussing whether it is reasonable that the complexity is high.

### PR DESCRIPTION
**Pull request by emilelm96**
Wrote the purpose description and answered the other questions of part 1 of the assignment.

(Should) fix #18.

### CODE REVIEW

**Review by Samuelhertzberg — CHANGES_REQUESTED** [review]
First paragraph is written in first person. This should be avoided ୧( ಠ Д ಠ )୨

**Comment by emilelm96** [comment]
Yes, I will change that, however the bigger issue right now I think is that I'm not getting the correct CC (23 instead of 24). I get 21 if statements and one try statement. 21 + 1 + 1 = 23 < 24. I don't understand what I'm getting wrong.

**Comment by Samuelhertzberg** [comment]
Maybe `return iter.readBoolean() ? "true" : "false";`
It's just an if with syntax sugar

**Comment by emilelm96** [comment]
Oh, yeah, true. Missed that one. Thank you.

**Review by Samuelhertzberg — APPROVED** [review]

**Review by Jonagoo — APPROVED** [review]

**Pull request merged**
